// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Sample2",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Sample2",
            targets: ["Demo2"],
            bundleIdentifier: "com.yochidros.Sample2",
            teamIdentifier: "X25KZ54NYC",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "SamplePackages", path: "../SamplePackages")
    ],
    targets: [
        .executableTarget(
            name: "Demo2",
            dependencies: [
                .product(name: "Package2Library", package: "SamplePackages", condition: nil),
            ]
        )
    ]
)
